server:
  port: 8762

spring:
  application:
    name: api-gateway

eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:eureka-server-production-efc6.up.railway.app}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://eureka-server-production-efc6.up.railway.app/eureka}

cloud:
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    routes:
      - id: ms-play-route
        uri: lb://ms-play
        predicates:
          - Path=/ms-play/**
        filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include: "*"

  endpoints:
    web:
      exposure:
        include: "*"
